# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63b97cdb64abf5a91cdc63bc0c50a729194a3d1aab986439c0b492bd98c4b0693e642c4c4a4aeed1f5a73d8a610b6fd41a4d589b907be74ccbc43a4106d02358

test:
  secret_key_base: 67ec6d9bf8daf71457262fb8fc4faed4dae75519aa15505185b75d82854855a6e6003abd15bccf70c48ddd63e361f58ea0e4921d855006ecd01fc429e83db68c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
